### ISSUE TITLE
LICENSE ?

### ISSUE THREAD

**Issue by lxj616** [bblanimation/rebrickr#2]
Hi, awesome work ! 
I didn't see any LICENSE within the repository
A LICENSE is vital to claim copyright and grant limited permission for those who took interest in your repository

Tips: what is a LICENSE
[https://help.github.com/articles/licensing-a-repository/](https://help.github.com/articles/licensing-a-repository/)
[https://opensource.org/licenses](https://opensource.org/licenses)

Or if it is not intended to be open source, in that case you may consider using private repository to protect your code

[https://help.github.com/articles/making-a-public-repository-private/](https://help.github.com/articles/making-a-public-repository-private/)

**Comment by bblanimation** [comment]
Hello,

Thank you for the compliment! I have included the copyright terms at the top of each source file, as recommended by https://opensource.org/licenses/GPL-3.0

I was under the impression this was all that was required.
