### ISSUE TITLE
Bricker V1.5.0 error on Update Model

### ISSUE THREAD

**Issue by ClemPratty** [bblanimation/rebrickr#3]
[Bricker_Error_V1.5.0.txt](https://github.com/bblanimation/rebrickr/files/2164554/Bricker_Error_V1.5.0.txt)

**Comment by ClemPratty** [comment]
I re-did my steps and it appears adding a custom logo causes the issue.

[Bricker_Error_V1.5.0_02.txt](https://github.com/bblanimation/rebrickr/files/2164557/Bricker_Error_V1.5.0_02.txt)

**Comment by bblanimation** [comment]
Thank you for reporting this! I've fixed the bug for version 1.5.1.

**Comment by bblanimation** [comment]
Version 1.5.1 has been released, containing a fix for this bug.
