### ISSUE TITLE
Brickify Smoke Domain

### ISSUE THREAD

**Issue by ParallelMayhem** [bblanimation/rebrickr#4]
Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1.5.0
Platform Info:
   system   = Darwin
   platform = Darwin-17.6.0-x86_64-i386-64bit
   version  = Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
   python   = 3.5.3
Error:
EXCEPTION (<class 'UnboundLocalError'>): local variable 'y' referenced before assignment
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-0/lib/bricksDict/generate.py
000 0405:getBrickMatrixSmoke() old_percent = updateProgressBars(printStatus, cursorStatus, (x * y * z) / denom, old_percent, "Shell")
001 0629:makeBricksDict() brickFreqMatrix, smokeColors = getBrickMatrixSmoke(origSource, faceIdxMatrix, cm.brickShell, source_details, cursorStatus=cursorStatus)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-0/functions/wrappers.py
002 0037:wrapped() ret = fn(*args, **kwargs)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-0/lib/bricksDict/storage.py
003 0058:getBricksDict() bricksDict = makeBricksDict(source, source_details, brickScale, origSource=origSource, cursorStatus=updateCursor)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-0/buttons/brickify.py
004 0450:createNewBricks() bricksDict, loadedFromCache = getBricksDict(dType=action, source=source, source_details=source_details, dimensions=dimensions, brickScale=brickScale2, updateCursor=updateCursor, curFrame=curFrame, origSource=origSource, restrictContext=False)
005 0288:brickifyModel() group_name = self.createNewBricks(sourceDup, parent, sourceDup_details, dimensions, refLogo, logo_details, self.action, split=cm.splitModel, curFrame=None, sceneCurFrame=None, origSource=self.source)
006 0167:runBrickify() self.brickifyModel(scn, cm, n, matrixDirty, skipTransAndAnimData)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-0/functions/wrappers.py
007 0037:wrapped() ret = fn(*args, **kwargs)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-0/buttons/brickify.py
008 0089:execute() self.runBrickify(context)

**Comment by bblanimation** [comment]
Thank you for reporting this issue! The bug has been fixed for version 1.5.1

**Comment by bblanimation** [comment]
Version 1.5.1 has been released, containing a fix for this bug.
